### PR TITLE
Update tests to use py.test

### PR DESCRIPTION
**Pull request by daf**

### CODE REVIEW

**Comment by daf** [comment]
Was really confused why travis ran, but now I see it's because of #11.  I'll fixup.

**Comment by ocefpaf** [comment]
Sorry for not giving you a heads up.  I did not use `py.test` in my PR because I am not sure how long will `wicken`+`petulant-bear` will be around.  (Maybe we should just admit that they are not going away and start supporting them.)

**Comment by daf** [comment]
For some reason this repo became un-watched, so I got no email - my fault entirely.  I don't plan on doing anything else to wicken other than making it py.test compliant, because that's what I'd expect in 2016.

**Comment by ocefpaf** [comment]
> because that's what I'd expect in 2016.

:+1: (BTW pytest is older than nose.  Nose just had better docs back then.)

**Pull request closed without merging**
